#!/usr/bin/env bash تم البرمجه من قبل القيصر علي العراقي                                                 
cd KENAE                                                                 
echo -e "\e[33m       
echo -e "\e[33m      
echo -e "\e[33m      
echo -e "\e[33m     
echo -e "\e[33m      
while(true) do      
lua start.lua
don
