#!/usr/bin/env bash     _  ____ _   _            
cd KENAE               | |/ /  ____| \ | |   /\   |  ____|  \e[0m"  
echo -e "\e[33m"       | ' /| |  |  \| |  /  \  | |__    \ e[0m"
echo -e "\e[33m "      |  < |  |   | . ` | / /\ \ | |        \e[0m"
echo -e "\e[33m  "     | . \| |____| |\  |/ ____ \| |____   \e[0m"
echo -e "\e[33m "      |_|\_\______|_| \_/_/    \_\______|  \e[0m"
echo -e "\e[33m  "  
while(true) do
lua start.lua 
done
