#!/usr/bin/env bash
cd KENAE                  _  ____ _   _          __  
echo -e "\e[33m"         | |/ /  ____| \ | |   /\   |  ____| \e[0m"
echo -e "\e[33m "        | ' /| |__  |  \| |  /  \  | |__     \ e[0m " 
echo -e "\e[33m  "       |  < | |    | . ` | / /\ \ | |         \e[0m "
echo -e "\e[33m "        | . \| |____| |\  |/ ____ \| |____    \e[0m "
echo -e "\e[33m  "       |_|\_\______|_| \_/_/    \_\______| \e[0m  "
while(true) do
lua start.lua 
done 
                                                                                                                                                                                                                                        
